### ISSUE TITLE
Remove API_KEY in .env file

### ISSUE THREAD

**Issue by SimaAmini** [raminr77/pin#1]
Hi @raminr77 
Google just notified me that you are using one of my Google maps API_KEYs publicly. Please remove sensitive information and never commit them to a public repository. 
This [article](https://dev.to/somedood/please-dont-commit-env-3o9h) might be helpful.
Thanks.

**Comment by raminr77** [comment]
Hi @SimaAmini 
I can't find any Google Map API keys in this project,
can you please commit a pull request or guide me to the file it exists in?

**Comment by SimaAmini** [comment]
I was referring to this [file](https://github.com/raminr77/pin/blob/master/src/env/env.ts)

**Comment by raminr77** [comment]
Tnx.
